# Recommended Hyperparameters from Blueprint

# 13.1 Retrieval / NLP Configuration
CHUNK_SIZE = 350
CHUNK_OVERLAP = 50
DENSE_TOP_K = 12
BM25_TOP_K = 12
GRAPH_TOP_K = 10
RRF_CANDIDATES = 20
RERANK_TOP_K = 20
FINAL_EVIDENCE_K = 6
MAX_RETRIEVAL_STEPS = 3

# 13.2 Confidence Configuration
ANSWER_SUPPORT_THRESHOLD = 0.80  # initial gate
WARNING_THRESHOLD = 0.65       # initial gate
MIN_EVIDENCE = 1
SYNTHESIS_MIN_EVIDENCE = 2

# 13.3 DQN Configuration
RL_LEARNING_RATE = 1e-4
RL_BUFFER_SIZE = 50000
RL_LEARNING_STARTS = 1000
RL_BATCH_SIZE = 64
RL_GAMMA = 0.95
RL_TRAIN_FREQ = 4
RL_GRADIENT_STEPS = 1
RL_TARGET_UPDATE_INTERVAL = 2000
RL_EXPLORATION_INITIAL_EPS = 1.0
RL_EXPLORATION_FINAL_EPS = 0.05
RL_EXPLORATION_FRACTION = 0.20
RL_POLICY_NETWORK = [128, 128]

# 13.4 Generator Configuration
LLM_CONTEXT_TOKENS = 8192
LLM_TEMPERATURE = 0.15
LLM_TOP_P = 0.85
LLM_TOP_K = 20
LLM_MAX_NEW_TOKENS = 1000

# Paths
DB_PATH = "data/research_vault.db"
VECTOR_INDEX_PATH = "data/faiss_index.bin"
GRAPH_PATH = "data/knowledge_graph.graphml"
